/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/desk.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/desk.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.45, 15.917, 0.262]}>
        <mesh geometry={nodes.polySurface213_chair_wood1_0_1.geometry} material={materials.chair_wood1} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_2.geometry} material={materials.table_wood1} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_3.geometry} material={materials.table_wood2} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_4.geometry} material={materials.pen_holder} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_5.geometry} material={materials.system_cpu} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_6.geometry} material={materials.system_mouse} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_7.geometry} material={materials.system_monitor} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_8.geometry} material={materials.system_keyboard} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_9.geometry} material={materials.book} />
        <mesh geometry={nodes.polySurface213_chair_wood1_0_10.geometry} material={materials.chair_cushion} />
      </group>
      <mesh geometry={nodes['monitor-screen'].geometry} material={nodes['monitor-screen'].material} position={[-1.49, 25.89, -0.354]} rotation={[0, 0, -Math.PI / 2]} scale={[3.37, 0.979, 5.153]} />
    </group>
  )
}

useGLTF.preload('/desk.glb')
