/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/desk.glb
Modified: monitor-screen mesh accepts a terminal canvas texture
*/

import { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { useLoaderContext } from './LoaderContext';

export function Desk(props) {
  const { nodes, materials } = useGLTF('./models/desk.glb');
  const { canvasRef, phase } = useLoaderContext();

  // Stable refs — never reassigned after creation, never cleaned up mid-life
  const texRef     = useRef(null);
  const matRef     = useRef(null);
  const meshRef    = useRef(null);
  const appliedRef = useRef(false); // guard: apply texture only once

  // Build texture exactly once when phase hits 'zooming'
  // No cleanup return — we keep it alive for the entire session
  useEffect(() => {
    if (appliedRef.current) return;           // already done
    if (phase !== 'zooming') return;
    const canvas = canvasRef.current;
    if (!canvas) return;

    appliedRef.current = true;

    const tex = new THREE.CanvasTexture(canvas);
    tex.flipY    = false;
    tex.rotation = -Math.PI / 2;
    tex.center.set(0.5, 0.5);
    tex.needsUpdate = true;
    texRef.current  = tex;

    const mat = new THREE.MeshBasicMaterial({ map: tex, toneMapped: false });
    matRef.current = mat;

    // Apply directly to the mesh imperatively — bypasses React re-render entirely
    if (meshRef.current) {
      meshRef.current.material = mat;
    }
  }, [phase, canvasRef]);

  // useFrame as a safety net: if the mesh re-renders and loses the material,
  // re-apply it every frame until done (zero cost once stable)
  useFrame(() => {
    if (!meshRef.current || !matRef.current) return;
    if (meshRef.current.material !== matRef.current) {
      meshRef.current.material = matRef.current;
    }
  });

  // Unmount cleanup only
  useEffect(() => {
    return () => {
      texRef.current?.dispose();
      matRef.current?.dispose();
    };
  }, []);

  return (
    <group {...props} dispose={null}>
      <group position={[3.45, 15.917, 0.262]}>
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_1.geometry} material={materials.chair_wood1} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_2.geometry} material={materials.table_wood1} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_3.geometry} material={materials.table_wood2} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_4.geometry} material={materials.pen_holder} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_5.geometry} material={materials.system_cpu} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_6.geometry} material={materials.system_mouse} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_7.geometry} material={materials.system_monitor} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_8.geometry} material={materials.system_keyboard} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_9.geometry} material={materials.book} />
        <mesh castShadow receiveShadow geometry={nodes.polySurface213_chair_wood1_0_10.geometry} material={materials.chair_cushion} />
      </group>

      {/* ref on the screen mesh so we can apply the texture imperatively */}
      <mesh
        ref={meshRef}
        castShadow
        receiveShadow
        geometry={nodes['monitor-screen'].geometry}
        material={nodes['monitor-screen'].material}
        position={[-1.49, 25.89, -0.354]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[3.37, 0.979, 5.153]}
      />
    </group>
  );
}

useGLTF.preload('./models/desk.glb');
