name: Deploy Express App

on:
  push:
    branches: ["stable"]
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version: "20"

          - name: Install dependencies
            working-directory: server
            run: npm install
            

          - name: Deploy Express App
            working-directory: server
            run: npm run start
            
