name: Run Tests

on:
  push:
    branches: ["stable"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
        env: 
          EMAILJS_ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          EMAILJS_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          EMAILJS_SERVICE_ID: ${{ secrets.SERVICE_ID }}
          EMAILJS_TEMPLATE_ADMIN: ${{ secrets.TEMPLATE_ADMIN }}
          EMAILJS_TEMPLATE_USER: ${{ secrets.TEMPLATE_USER }}
